/**
 * Constants used for fuzzy search functionality
 */

/**
 * Common stop words to filter out from search queries
 */
export const STOP_WORDS = new Set([
  "the",
  "a",
  "an",
  "and",
  "or",
  "but",
  "in",
  "on",
  "at",
  "to",
  "for",
  "with",
  "by",
  "of",
  "from",
  "as",
  "poster",
  "posters",
]);

/**
 * Common multi-word cities that might be searched for
 */
export const MULTI_WORD_CITIES = [
  "new york",
  "los angeles",
  "san francisco",
  "san diego",
  "san jose",
  "san antonio",
  "las vegas",
  "salt lake city",
  "jersey city",
  "mexico city",
  "new orleans",
  "st. louis",
  "st louis",
  "kansas city",
  "oklahoma city",
  "fort lauderdale",
  "fort worth",
  "fort collins",
  "santa fe",
  "santa cruz",
  "santa monica",
  "santa barbara",
  "santa rosa",
  "baton rouge",
  "coral gables",
  "coral springs",
  "grand rapids",
  "grand junction",
  "north charleston",
  "west palm beach",
  "palm springs",
  "palm desert",
  "long beach",
  "virginia beach",
  "newport beach",
  "south bend",
  "colorado springs",
  "iowa city",
  "atlantic city",
  "cedar rapids",
  "lake tahoe",
  "des moines",
  "el paso",
  "san bernardino",
  "palo alto",
  "rio rancho",
  "green bay",
  "black mountain",
  "red hook",
  "red bank",
  "mount vernon",
  "new haven",
  "new brunswick",
  "new rochelle",
];

/**
 * List of common venue-related keywords
 */
export const VENUE_KEYWORDS = [
  "arena",
  "theater",
  "theatre",
  "hall",
  "center",
  "centre",
  "stadium",
  "garden",
  "gardens",
  "coliseum",
  "pavilion",
  "amphitheatre",
  "amphitheater",
  "auditorium",
  "convention",
  "fairgrounds",
  "park",
  "square",
  "forum",
  "bowl",
  "palace",
  "ballroom",
  "opera",
  "civic",
  "festival",
  "club",
  "lounge",
  "concert hall",
  "music hall",
  "performing arts",
  "venue",
  "stage",
  "grounds",
  "house of blues",
  "fillmore",
  "bowl",
  "field",
  "farm",
  "center stage",
  "casino",
  "pier",
  "dome",
  "music box",
  "tabernacle",
  "ryman",
  "beacon",
  "paramount",
  "fox theater",
  "civic center",
  "nightclub",
  "bar",
  "pub",
];

/**
 * Specific well-known venues that might not be covered by individual keywords
 */
export const SPECIFIC_VENUES = [
  "red rocks",
  "hollywood bowl",
  "madison square garden",
  "the forum",
  "the gorge",
  "msg",
  "barclays center",
  "greek theatre",
];

/**
 * List of well-known music venue cities
 */
export const COMMON_CITIES = [
  "new york",
  "los angeles",
  "chicago",
  "seattle",
  "portland",
  "boston",
  "austin",
  "nashville",
  "miami",
  "denver",
  "boulder",
  "san francisco",
  "oakland",
  "berkeley",
  "las vegas",
  "atlanta",
  "dallas",
  "houston",
  "philadelphia",
  "washington",
  "toronto",
  "montreal",
  "vancouver",
  "london",
  // Additional cities
  "detroit",
  "minneapolis",
  "st paul",
  "san diego",
  "phoenix",
  "tucson",
  "sacramento",
  "memphis",
  "new orleans",
  "charlotte",
  "raleigh",
  "durham",
  "charleston",
  "savannah",
  "orlando",
  "tampa",
  "cleveland",
  "cincinnati",
  "columbus",
  "pittsburgh",
  "buffalo",
  "syracuse",
  "albany",
  "providence",
  "hartford",
  "omaha",
  "kansas city",
  "st louis",
  "milwaukee",
  "indianapolis",
  "louisville",
  "lexington",
  "birmingham",
  "richmond",
  "baltimore",
  "san jose",
  "albuquerque",
  "santa fe",
  "salt lake city",
  "boise",
  "spokane",
  "eugene",
  "tacoma",
  "olympia",
  "san antonio",
  "fort worth",
  "oklahoma city",
  "tulsa",
  "wichita",
  "des moines",
  "grand rapids",
  "madison",
  "ann arbor",
  "burlington",
  "hollywood",
];

/**
 * Month names for matching in date extraction
 */
export const MONTH_NAMES = [
  "january",
  "february",
  "march",
  "april",
  "may",
  "june",
  "july",
  "august",
  "september",
  "october",
  "november",
  "december",
];
