name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # Build frontend
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Build backend
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Build backend
        working-directory: ./backend
        run: npm run build

      # Deploy
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key verification
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          # Transfer backend files
          rsync -avz --delete backend/dist/ $SSH_USER@$SSH_HOST:/var/www/concert-poster-marketplace/backend/dist/

          # Transfer frontend files
          rsync -avz --delete frontend/dist/ $SSH_USER@$SSH_HOST:/var/www/concert-poster-marketplace/frontend/dist/

          # Execute deployment script on server
          ssh $SSH_USER@$SSH_HOST 'cd /var/www/concert-poster-marketplace && bash deploy.sh'
